// This lists all categories as well as subcategories
export const LIST_ALL_CATEGORY_START = "LIST_ALL_CATEGORY_START";
export const LIST_ALL_CATEGORY_SUCCESS = "LIST_ALL_CATEGORY_SUCCESS";
export const LIST_ALL_CATEGORY_FAILURE = "LIST_ALL_CATEGORY_FAILURE";

export const LIST_CATEGORY_START = "LIST_CATEGORY_START";
export const LIST_CATEGORY_SUCCESS = "LIST_CATEGORY_SUCCESS";
export const LIST_CATEGORY_FAILURE = "LIST_CATEGORY_FAILURE";

export const CREATE_CATEGORY_START = "CREATE_CATEGORY_START";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

export const UPDATE_CATEGORY_START = "UPDATE_CATEGORY_START";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

export const LIST_SUBCATEGORY_START = "LIST_SUBCATEGORY_START";
export const LIST_SUBCATEGORY_SUCCESS = "LIST_SUBCATEGORY_SUCCESS";
export const LIST_SUBCATEGORY_FAILURE = "LIST_SUBCATEGORY_FAILURE";

export const CREATE_SUBCATEGORY_START = "CREATE_SUBCATEGORY_START";
export const CREATE_SUBCATEGORY_SUCCESS = "CREATE_SUBCATEGORY_SUCCESS";
export const CREATE_SUBCATEGORY_FAILURE = "CREATE_SUBCATEGORY_FAILURE";

export const DELETE_SUBCATEGORY_START = "DELETE_SUBCATEGORY_START";
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS";
export const DELETE_SUBCATEGORY_FAILURE = "DELETE_SUBCATEGORY_FAILURE";

export const UPDATE_SUBCATEGORY_START = "UPDATE_SUBCATEGORY_START";
export const UPDATE_SUBCATEGORY_SUCCESS = "UPDATE_SUBCATEGORY_SUCCESS";
export const UPDATE_SUBCATEGORY_FAILURE = "UPDATE_SUBCATEGORY_FAILURE";
