export const GET_PRODUCTS_OF_USER_START = 'GET_PRODUCTS_OF_USER_START';
export const GET_PRODUCTS_OF_USER_SUCCESS = 'GET_PRODUCTS_OF_USER_SUCCESS';
export const GET_PRODUCTS_OF_USER_ERROR = 'GET_PRODUCTS_OF_USER_ERROR';