export const GET_ORDERS_OF_VENDOR_START = 'GET_ORDERS_OF_VENDOR_START';
export const GET_ORDERS_OF_VENDOR_SUCCESS = 'GET_ORDERS_OF_VENDOR_SUCCESS';
export const GET_ORDERS_OF_VENDOR_FAILURE = 'GET_ORDERS_OF_VENDOR_FAILURE';
